# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-26 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='print_details',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
