# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-26 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_order_print_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='print_details',
            field=models.CharField(max_length=100),
        ),
    ]
