# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-18 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Baby', 'BABY PRINTS'), ('Christening Prints', 'CHRISTENING PRINTS'), ('Engagement Prints', 'ENGAGEMENT PRINTS'), ('Wedding Prints', 'WEDDING PRINTS'), ('Family Prints', 'FAMILY PRINTS')], default='baby prints', max_length=30),
        ),
    ]
