# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-26 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('baby', 'BABY'), ('christening', 'CHRISTENING'), ('communion', 'COMMUNION'), ('engagement-anniversary', 'ENGAGEMENT-ANNIVERSARY'), ('family', 'FAMILY'), ('fingerprint', 'FINGERPRINT'), ('mothersdayfathersday', 'MOTHERSDAY/FATHERSDAY'), ('teacher', 'TEACHER'), ('wedding', 'WEDDING')], default='baby', max_length=30),
        ),
    ]
