# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-27 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200426_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Anniversary', 'ANNIVERSARY'), ('Baby', 'BABY'), ('Christening', 'CHRISTENING'), ('Communion', 'COMMUNION'), ('Engagement', 'ENGAGEMENT'), ('Family', 'FAMILY'), ('Fathers', 'FATHERS'), ('Fingerprint', 'FINGERPRINT'), ('Mothers', 'MOTHERS'), ('Teacher', 'TEACHER'), ('Wedding', 'WEDDING')], default='baby', max_length=30),
        ),
    ]
