# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-20 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Baby', 'BABY PRINTS'), ('Christening', 'CHRISTENING PRINTS'), ('Engagement', 'ENGAGEMENT PRINTS'), ('Wedding', 'WEDDING PRINTS'), ('Family', 'FAMILY PRINTS')], default='baby prints', max_length=30),
        ),
    ]
