# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-20 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('baby', 'baby'), ('christening', 'christening'), ('engagement', 'engagement'), ('wedding', 'wedding'), ('family', 'family')], default='baby', max_length=30),
        ),
    ]
