# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-21 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20200421_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Baby', 'BABY'), ('christening', 'CHRISTENING'), ('communion', 'COMMUNION'), ('engagement', 'ENGAGEMENT'), ('family', 'FAMILY'), ('fathersday', 'FATHERSDAY'), ('fingerprint', 'FINGERPRINT'), ('mothersday', 'MOTHERSDAY'), ('teacher', 'TEACHER'), ('wedding', 'WEDDING')], default='', max_length=30),
        ),
    ]
